version: '3.3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=pyrodark
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    restart: always
  darkpyro:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    restart: always